skripsipedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_app.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web_app/urls.py
from django.urls import URLPattern, path
from web_app import views

urlpatterns = [
    #login
    path('', views.loginPage, name='loginPage'),
    path('', views.logoutUser, name='logoutUser'),

    #registrasi
    path('registrasi', views.registrasi, name='registrasi'),
    
    #laa
    path('laa/dashboard', views.dashboardLAA, name='dashboardLAA'),
    path('laa/permintaan-sidang', views.reqSidangTA, name='reqSidangTA'),
    path('laa/permintaan-sidang/hapus/<str:pk>', views.hapusReqSidang, name='hapusReqSidang'),
    path('laa/permintaan-sidang/terima/<str:pk>', views.terimaReqSidang, name='terimaReqSidang'),
    path('laa/jadwal-sidang', views.jadwalSidangLAA, name='jadwalSidangLAA'),
    path('akun/laa/pengaturan', views.pengaturanLAA, name='pengaturanLAA'),
    path('akun/laa/ubah-password', views.ubahPasswordLAA, name='ubahPasswordLAA'),
    
    #dosen
    path('dosen-pembimbing/dashboard', views.dashboardDosen, name='dashboardDosen'),
    path('dosen-pembimbing/input-proposal', views.inputProposal, name='inputProposal'),
    path('dosen-pembimbing/daftar-mahasiswa', views.daftarMahasiswa, name='daftarMahasiswa'),
    path('akun/dosen-pembimbing/profil-dosen', views.profilDosen, name='profilDosen'),
    path('akun/dosen-pembimbing/pengaturan-dosen', views.pengaturanDosen, name='pengaturanDosen'),
    path('akun/dosen-pembimbing/ubah-password', views.ubahPasswordDosen, name='ubahPasswordDosen'),
    path('profil/mahasiswa/<str:pk>', views.lihatProfil, name='lihatProfil'),
    path('media/', views.view_pdf, name='lihatNilai'),
    path('dosen-pembimbing/list-proposal', views.listProposal, name='listProposal'),
    path('editProposal/<str:pk>', views.editProposal, name='editProposal'),
    path('tolakMahasiswa/<str:pk>', views.hapusApply, name='tolakMahasiswa'),
    path('dosen-pembimbing/jadwal-kuliah', views.jadwalKuliah, name='jadwalKuliah'),
    path('hapusJadwalKuliah/<str:pk>', views.hapusJadwalKuliah, name='hapusJadwalKuliah'),
    path('dosen-pembimbing/input-jadwal-dosen', views.inputJadwalKuliah, name='inputJadwalDosen'),
    path('dosen-pembimbing/jadwal-sidang', views.jadwalSidangTADP, name='jadwalSidangTA'),
    path('hapusProposal/<str:pk>', views.hapusProposal, name='hapusProposal'),
    path('updateStatus/<str:pk>', views.updateStatus, name='updateStatus'),
    path('dosen-pembimbing/input-nilai-ta/<str:pk>', views.inputNilaiTA, name='inputNilaiTA'),
    path('dosen-pembimbing/input-revisi-ta/<str:pk>', views.revisiTA, name='inputRevisiTA'),

    #Dosen Fungsional
    path('dosen-fungsional/dashboard', views.dashboardDosenFungsional, name='dashboardDosenFungsional'),
    path('dosen-fungsional/list-permintaan-sidang', views.listRequest, name='listRequestJadwal'),
    path('generateJadwal', views.generateJadwal, name='generateJadwal'),
    path('dosen-fungsional/hasil-jadwal', views.hasilJadwal, name='hasilJadwal'),
    path('dosen-fungsional/ruang-sidang', views.ruangSidang, name='ruangSidang'),
    path('editJadwal/<str:pk>', views.editJadwal, name='editJadwal'),
    path('dosen-fungsional/tambah-ruang-sidang', views.tambahRuangSidang, name='tambahRuangSidang'),
    path('hapusRuangSidang/<str:pk>', views.hapusRuang, name='hapusRuangSidang'),
    path('akun/dosen-fungsional/pengaturan', views.pengaturanDF, name='pengaturanDF'),

    #Dosen Matkul
    path('dosen-matkul/dashboard', views.dashboardDosenMatkul, name='dashboardDosenMatkul'),
    path('dosen-matkul/nilai', views.nilai, name='nilai'),
    path('inputNilai/<str:pk>', views.inputNilai, name='inputNilai'),
    path('dosen-matkul/jadwal-sempro', views.jadwalSempro, name='jadwalSempro'),
    path('editSempro/<str:pk>', views.ubahJadwalSempro, name='editSempro'),
    path('dosen-matkul/file-proposal', views.fileProposal, name='fileProposal'),
    path('dosen-pembimbing/pengaturan-jadwal-sempro', views.pengaturanJadwalSempro, name='pengaturanJadwalSempro'),
    path('input-jadwal-sempro', views.inputJadwalSempro, name='inputJadwalSempro'),
    path('hapusJadwalSempro/<str:pk>', views.hapusJadwalSempro, name='hapusJadwalSempro'),
    path('hapusJamSempro/<str:pk>', views.hapusJamSempro, name='hapusJamSempro'),
    path('akun/dosen-matkul/ubah-password', views.ubahPasswordDM, name='ubahPasswordDM'),
   
    #mahasiswa
    path('mahasiswa/dashboard', views.dashboardMahasiswa, name='dashboardMahasiswa'),
    path('mahasiswa/proposal', views.proposal, name='proposal'),
    path('detail-proposal/<int:id>', views.detailProposal, name='detailProposal'),
    path('mahasiswa/sidangTA', views.sidangTA, name='sidangTA'),
    path('mahasiswa/seminar-proposal', views.seminarProposal, name='seminarProposal'),
    path('mahasiswa/upload-revisi', views.uploadRevisi, name='uploadRevisi'),
    path('mahasiswa/status-proposal', views.statusDiterima, name='statusDiterima'),
    path('akun/mahasiswa/pengaturan-mahasiswa', views.pengaturanMahasiswa, name='pengaturanMahasiswa'),
    path('akun/mahasiswa/ubah-password-mahasiswa', views.ubahPasswordMahasiswa, name='ubahPasswordMahasiswa'),
    path('akun/mahasiswa/tambah-kelas', views.tambahKelas, name='tambahKelas'),
    path('mahasiswa/nilai-proposal', views.nilaiProposal, name='nilaiProposal'),
    path('mahasiswa/nilai-tugas-akhir', views.nilaiTA, name='nilaiTA'),
    path('tutorial', views.tutorial, name='tutorial'),
    path('akun/mahasiswa/profil-mahasiswa', views.profilMahasiswa, name='profilMahasiswa'),
    path('akun/mahasiswa/lengkapi-profil', views.lengkapiProfil, name='lengkapiProfil'),
    path('mahasiswa/jadwal-sidang', views.jadwalSidangMhs, name='jadwalSidangMhs'),
    path('mahasiswa/jadwal-sempro', views.jadwalSemproMhs, name='jadwalSemproMhs'),

    #404 Error
    path('error403', views.error403, name='error403'),
    path('error', views.errorExist, name='errorExist'),

    #Ajax
    path('ajax/load-kelas/', views.load_kelas, name='ajax_load_kelas'),
]

web_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Angkatan(models.Model):
    nama = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.nama)

class Kelas(models.Model):
    angkatan = models.ForeignKey(Angkatan, null=True, on_delete=models.CASCADE)
    nama = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.nama)

class User_Kelas(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True, null=True)
    angkatan = models.ForeignKey(Angkatan, on_delete=models.SET_NULL, blank=True, null=True)
    kelas = models.ForeignKey(Kelas, on_delete=models.SET_NULL, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

class Lab(models.Model):
    nama = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.nama)

class Profil_Mahasiswa(models.Model):
    user = models.OneToOneField(User, null= True, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, null=True)
    nim = models.IntegerField(null=True)
    email = models.CharField(max_length=200, null=True)
    bakat = models.CharField(max_length=200, null=True)
    foto_profil = models.ImageField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    berkas_nilai = models.FileField(upload_to='pdf/nilai', storage=None, max_length=200)
    nilai_proposal = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    individual_performance = models.IntegerField(null=True, blank=True)
    CD_1 = models.IntegerField(null=True, blank=True)
    CD_2 = models.IntegerField(null=True, blank=True)
    CD_3 = models.IntegerField(null=True, blank=True)
    presentation = models.IntegerField(null=True, blank=True)
    individual_performance_ta = models.IntegerField(null=True, blank=True)
    progress_report = models.IntegerField(null=True, blank=True)
    final_report = models.IntegerField(null=True, blank=True)
    presentasi_demo = models.IntegerField(null=True, blank=True)
    paper = models.IntegerField(null=True, blank=True)
    buku_ta = models.IntegerField(null=True, blank=True)
    sidang_ta = models.IntegerField(null=True, blank=True)
    nilai_ta = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    revisi = models.CharField(max_length=10000, blank=True, null=True)
    batas_revisi = models.CharField(max_length=200, blank=True, null=True)
    hari_ini = models.CharField(max_length=200, blank=True, null=True)
    judul_ta = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return str(self.nama)

class Profil_Staff(models.Model):
    labs = (
        ('Seculab', 'Seculab'),
        ('SEA', 'SEA'),
        ('Rnest', 'Rnest'),
        ('Magics', 'Magics'),
        ('I-Smile', 'I-Smile'),
        ('Evconn', 'Evconn'),
    )
    user = models.OneToOneField(User, null= True, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, null=True)
    nip = models.CharField(max_length=200, null=True)
    kode_dosen = models.CharField(max_length=5, null=True)
    kelompok_keahlian = models.CharField(max_length = 200, choices=labs, null=True)
    email = models.CharField(max_length=200, null=True)
    foto_profil = models.ImageField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.kode_dosen)

class Proposal(models.Model):
    user = models.ForeignKey(User, null= True, on_delete=models.CASCADE)
    judul = models.CharField(max_length=200, null=True, blank=True)
    skill = models.CharField(max_length=200, null=True, blank=True)
    pbb1 = models.CharField(max_length=200, null=True, blank=True)
    pbb2 = models.CharField(max_length=200, null=True, blank=True)
    pengusul = models.CharField(max_length=200, null=True)
    lab = models.CharField(max_length=200, null=True, blank=True)
    jml_mhs = models.IntegerField(null=True, blank=True)
    penelitian_sebelumnya = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.judul)

class Order(models.Model):
    user = models.OneToOneField(User, null= True, on_delete=models.CASCADE)
    proposal = models.OneToOneField(Proposal, null=True, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        return str(self.proposal)

class File(models.Model):
    user = models.OneToOneField(User, null= True, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, null=True)
    nim = models.IntegerField(null=True)
    fakultas = models.CharField(max_length=200, null=True)
    revisi = models.FileField(upload_to='pdf/revisi',storage=None, max_length=200, blank=True)
    lembar_ta = models.FileField(upload_to='pdf/lembar_ta',storage=None, max_length=200, blank=True)
    jurnal = models.FileField(upload_to='pdf/jurnal',storage=None, max_length=200, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.nama)

class Sempro(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, null=True)
    nim = models.IntegerField(null=True)
    kelas = models.CharField(max_length=50, null=True)
    tanggal = models.CharField(max_length=200, null=True, blank=True)
    jam = models.CharField(max_length=200, null=True, blank=True)
    pbb1 = models.CharField(max_length=50, null=True)
    pbb2 = models.CharField(max_length=50, null=True)
    judul = models.CharField(max_length=200, null=True)
    cd1 = models.FileField(upload_to='pdf/CD1/', storage=None, null=True, max_length=200)
    cd2 = models.FileField(upload_to='pdf/CD2/', storage=None, null=True, max_length=200)
    cd3 = models.FileField(upload_to='pdf/CD3/', storage=None, null=True, max_length=200)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.nama)

# Tambahkan ruang sidang
class RuangSidang(models.Model):
    nama_ruang = models.CharField(max_length = 100)
    def __str__(self):
        return str(self.nama_ruang)

class DaftarSidang(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, null=True)
    nim = models.IntegerField(null=True)
    judul_indo = models.CharField(max_length=400, null=True)
    pbb1 = models.CharField(max_length=100, null=True)
    pbb2 = models.CharField(max_length=100, null=True)
    hari_sidang = models.CharField(max_length=200, null=True)
    waktu_sidang = models.CharField(max_length=100, null=True)
    kelompok_keahlian = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=200, null=True)
    kelas = models.CharField(max_length=100, null=True)
    prodi = models.CharField(max_length=100, null=True)
    tak = models.IntegerField(null=True)
    eprt = models.IntegerField(null=True)
    judul_inggris = models.CharField(max_length=400, null=True)
    whatsapp = models.BigIntegerField(null=True)
    persetujuan = models.CharField(max_length=50, null= True)
    berkas = models.FileField(upload_to='pdf/sidang/', storage=None, max_length=200)
    status = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.nama)

class JadwalKelasDosen(models.Model):
    day = (
        ('Senin', 'Senin'),
        ('Selasa', 'Selasa'),
        ('Rabu', 'Rabu'),
        ('Kamis', 'Kamis'),
        ('Jumat', 'Jumat'),
    )
    jam = (
        ('08:30 - 10.30', '08:30 - 10.30'),
        ('10:30 - 12.30', '10:30 - 12.30'),
        ('12:30 - 14.30', '12:30 - 14.30'),
        ('14:30 - 16.30', '14:30 - 16.30'),
    )
    dosen = models.ForeignKey(Profil_Staff, null=True, on_delete=models.CASCADE)
    hari = models.CharField(max_length=200, choices=day, null=True)
    waktu = models.CharField(max_length=200, choices=jam, null=True)
    def __str__(self):
        return str(self.dosen)
    
# Model untuk tabel hasil jadwal sidang
class JadwalSidang(models.Model):
    daftar_sidang = models.ForeignKey(DaftarSidang, null=True, on_delete=models.CASCADE)
    penguji1 = models.ForeignKey(Profil_Staff, null=True, on_delete=models.CASCADE, related_name='penguji1')
    penguji2 = models.ForeignKey(Profil_Staff, null=True, on_delete=models.CASCADE, related_name='penguji2')
    ruang = models.ForeignKey(RuangSidang, null=True, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

class JadwalSemproDosen(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    tanggal = models.CharField(max_length=200, null=True)

class JamSemproDosen(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    jam_mulai = models.CharField(max_length=200, null=True)
    jam_selesai = models.CharField(max_length=200, null=True)

web_app/templates/mahasiswa/home/dashboardMahasiswa.html
<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Skripsipedia</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   {% load static %}
   <!-- Include CSS files -->
   {% include 'mahasiswa/includes/css.html' %}
   <!-- Specific CSS goes HERE -->
   {% block stylesheets %}

   {% endblock stylesheets %}
   <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
</head>



{% include 'mahasiswa/includes/navigation.html' %}

{% block content %}

<div class="midde_cont">
   <div class="container-fluid">
      <div class="row column_title">
         <div class="col-md-12">
            <div class="page_title">
               <h2>Dashboard</h2>
            </div>
         </div>
      </div>
      {% include 'message.html' %}
      <div class="card" style="width: 70.8rem;">
         <div class=" card text-center">
            <div class="card-header">
               <h5>Pemberitahuan</h5>
            </div>
            <div class="card-body">
               <h5 class="card-text">Pendaftaran sidang bulan februari akan dilaksanakan pada 23-27 Januari
               </h5>
               <br>
               <a href="{% url 'sidangTA' %}" class="btn btn-primary">Link Daftar Sidang</a>
            </div>
            <div class="card-footer text-muted">
               LAA
            </div>
         </div>
      </div>
      <br>
      <div class="row column1">
         <div class="col-md-6 col-lg-3">
            <div class="full counter_section margin_bottom_30 yellow_bg">
               <div class="couter_icon">
                  <div>
                     <i class="fa fa-user"></i>
                  </div>
               </div>
               <div class="counter_no">
                  <div>
                     <p class="total_no">{{user_count}}
                     </p>
                     <p class="head_couter">User</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-md-6 col-lg-3">
            <div class="full counter_section margin_bottom_30 yellow_bg">
               <div class="couter_icon">
                  <div>
                     <i class="fa fa-user"></i>
                  </div>
               </div>
               <div class="counter_no">
                  <div>
                     <p class="total_no">{{mhs_count}}
                     </p>
                     <p class="head_couter">Mahasiswa</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-md-6 col-lg-3">
            <div class="full counter_section margin_bottom_30 yellow_bg">
               <div class="couter_icon">
                  <div>
                     <i class="fa fa-user"></i>
                  </div>
               </div>
               <div class="counter_no">
                  <div>
                     <p class="total_no">{{pbb_count}}
                     </p>
                     <p class="head_couter">Pembimbing</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-md-6 col-lg-3">
            <div class="full counter_section margin_bottom_30 yellow_bg">
               <div class="couter_icon">
                  <div>
                     <i class="fa fa-user"></i>
                  </div>
               </div>
               <div class="counter_no">
                  <div>
                     <p class="total_no">{{proposals}}
                     </p>
                     <p class="head_couter">Proposal</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>





{% include 'mahasiswa/includes/footer.html' %}
</div>
<!-- end dashboard inner -->
</div>

{% include 'mahasiswa/includes/scripts.html' %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}
</body>
{% endblock content %}

</html>

web_app/templates/mahasiswa/home/jadwalSempro.html
<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Skripsipedia</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   {% load static %}
   <!-- Include CSS files -->
   {% include 'mahasiswa/includes/css.html' %}
   <!-- Specific CSS goes HERE -->
   {% block stylesheets %}
   <style>
      .pagination {
         display: flex;
         justify-content: center;
      }

      .pagination .active>span {
         background-color: #000000;
         color: black;
      }

      .pagination button {
         padding: 0.5em 1em;
         margin: 0 0.25em;
      }
   </style>
   {% endblock stylesheets %}
   <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
</head>

{% include 'mahasiswa/includes/navigation.html' %}

{% block content %}

<!-- dashboard inner -->

<!-- row -->
<div class="row column1">
   <div class="col-md-13">
      <div class="white_shd full margin_bottom_30">
         <div class="full graph_head">
            <div class="heading1 margin_0">
               <h2>Jadwal Sempro</h2>
            </div>
         </div>
         {% include 'message.html' %}
         <div class="full price_table padding_infor_info">
            <div class="row">
               <div class="col-lg-12">
                  <div class="table-responsive-sm">
                     <table class="table table-striped projects">
                        <thead class="thead-dark">
                           <tr>
                              <th>Nama</th>
                              <th>Judul TA</th>
                              <th>Kelas</th>
                              <th>Tanggal</th>
                              <th>Jam</th>
                           </tr>
                        </thead>
                        <tbody>
                           <tr>
                              <td>
                                 <a>{{user.sempro.nama}}</a>
                              </td>
                              <td>
                                 <a>{{user.sempro.judul}}</a>
                              </td>
                              <td>
                                 <a>{{user.user_kelas.kelas}}</a>
                              </td>
                              <td>
                                 <a>{{user.sempro.tanggal}}</a>
                              </td>
                              <td>
                                 <a>{{user.sempro.jam}}</a>
                              </td>
                           </tr>

                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- end row -->
</div>
<!-- footer -->

{% include 'mahasiswa/includes/footer.html' %}
</div>
<!-- end dashboard inner -->
</div>
</div>
</div>
{% include 'mahasiswa/includes/scripts.html' %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}
</body>
{% endblock content %}

</html>

web_app/templates/mahasiswa/home/tambahKelas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Daftar Kelas Proposal</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--===============================================================================================-->
</head>
{% block content %}

<body>

    <div class="limiter">
        <div class="container-login100">
            {% include 'message.html' %}
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="{% static 'images/tk.png' %}" alt="IMG">
                </div>

                <form class="login100-form validate-form" method="POST" id="kelasForm"
                    data-kelas-url="{% url 'ajax_load_kelas' %}">
                    <span class="login100-form-title">
                        Daftar Kelas Proposal
                    </span>

                    {% csrf_token %}
                    {{form.as_p}}



                    <div class="container-login100-form-btn">
                        <button type="submit" class="login100-form-btn" role="button">
                            Submit
                        </button>
                    </div>



                </form>
            </div>
        </div>
    </div>

    {% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_angkatan").change(function () {
            const url = $("#kelasForm").attr("data-kelas-url");  // get the url of the `load_cities` view
            const angkatanId = $(this).val();  // get the selected country ID from the HTML input

            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'angkatan_id': angkatanId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_kelas").html(data);  // replace the contents of the city input with the data that came from the server
                    /*
    
                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (city) {
                        html_data += `<option value="${city.id}">${city.name}</option>`
                    });
                    console.log(html_data);
                    $("#id_city").html(html_data);
    
                    */
                }
            });

        });
    </script>
    {% endblock javascripts %}


    <!--===============================================================================================-->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'js/main.js' %}"></script>

</body>
{% endblock content %}

</html>